#' ---
#' title: "A report generated from a pure R script"
#' author: "Peter Reimann"
#' date: '2022-08-01'
#' output: powerpoint_presentation
#' ---


#' # R Markdown
#' 
#' This is a report generated by `knitr::spin()`.

#' This is an R Markdown presentation. 
#'  
#' Markdown is a simple formatting syntax for authoring HTML, PDF, and MS Word documents. 
#' For more details on using R Markdown see <http://rmarkdown.rstudio.com>.
#' 
#' When you click the **Knit** button a document will be generated 
#' that includes both content as well as the output of any embedded 
#' R code chunks within the document.
#' 
#' # Slide with Bullets
#' 
#' - Bullet 1
#' 
#' - Bullet 2
#' 
#' - Bullet 3
#' 
#' # Slide with R Output
#' 
#+ echo=FALSE, fig.width=7
#  This is a normal R comment.
plot(cars)
#'
#' # Slide with Plot
#'
#+ 
plot(pressure)